<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Load-dependencies" data-toc-modified-id="Load-dependencies-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Load dependencies</a></span></li><li><span><a href="#Read-csv-files-to-DFs" data-toc-modified-id="Read-csv-files-to-DFs-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Read csv files to DFs</a></span></li><li><span><a href="#Add-date-part" data-toc-modified-id="Add-date-part-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Add date part</a></span></li><li><span><a href="#Train-cats-for-the-DFs" data-toc-modified-id="Train-cats-for-the-DFs-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Train cats for the DFs</a></span></li><li><span><a href="#Add-extra-columns-(purchased-on-weekend,-monthend,-month_diff-etc." data-toc-modified-id="Add-extra-columns-(purchased-on-weekend,-monthend,-month_diff-etc.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Add extra columns (purchased on weekend, monthend, month_diff etc.</a></span></li><li><span><a href="#Fill-NAs-with-mode" data-toc-modified-id="Fill-NAs-with-mode-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Fill NAs with mode</a></span></li><li><span><a href="#Separate-the-authorised-and-non-authorised-transactions" data-toc-modified-id="Separate-the-authorised-and-non-authorised-transactions-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Separate the authorised and non-authorised transactions</a></span></li><li><span><a href="#proc_df-to-fill-nas,-one-hot-encode-cats" data-toc-modified-id="proc_df-to-fill-nas,-one-hot-encode-cats-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>proc_df to fill nas, one hot encode cats</a></span></li><li><span><a href="#Drop-unnecessary-columns" data-toc-modified-id="Drop-unnecessary-columns-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Drop unnecessary columns</a></span></li><li><span><a href="#Aggregate-by-card_id" data-toc-modified-id="Aggregate-by-card_id-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Aggregate by card_id</a></span></li><li><span><a href="#Add-exta-interpreted-columns-on-aggregates" data-toc-modified-id="Add-exta-interpreted-columns-on-aggregates-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Add exta interpreted columns on aggregates</a></span></li><li><span><a href="#Add-monthly-aggregates" data-toc-modified-id="Add-monthly-aggregates-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Add monthly aggregates</a></span></li><li><span><a href="#Add-successive-aggregates" data-toc-modified-id="Add-successive-aggregates-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Add successive aggregates</a></span></li><li><span><a href="#Merge-monthly-aggregates-and-successive-aggregates-dfs-with-other-aggregate-dfs" data-toc-modified-id="Merge-monthly-aggregates-and-successive-aggregates-dfs-with-other-aggregate-dfs-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Merge monthly aggregates and successive aggregates dfs with other aggregate dfs</a></span></li><li><span><a href="#Load-test-&amp;-train-DFs" data-toc-modified-id="Load-test-&amp;-train-DFs-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Load test &amp; train DFs</a></span></li><li><span><a href="#Add-date-part-to-test-&amp;-train-dfs" data-toc-modified-id="Add-date-part-to-test-&amp;-train-dfs-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Add date part to test &amp; train dfs</a></span></li><li><span><a href="#Merge-train-&amp;-test-with-new-&amp;-old-transactions-history" data-toc-modified-id="Merge-train-&amp;-test-with-new-&amp;-old-transactions-history-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>Merge train &amp; test with new &amp; old transactions history</a></span></li><li><span><a href="#Add-extra-columns-like-age,-total-transactions,-installments,-purchase-amount,-first-buy-etc" data-toc-modified-id="Add-extra-columns-like-age,-total-transactions,-installments,-purchase-amount,-first-buy-etc-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>Add extra columns like age, total transactions, installments, purchase amount, first buy etc</a></span></li><li><span><a href="#Mark-the-outliers" data-toc-modified-id="Mark-the-outliers-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>Mark the outliers</a></span></li><li><span><a href="#Target-encode-the-outliers---no-improvements" data-toc-modified-id="Target-encode-the-outliers---no-improvements-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>Target encode the outliers - no improvements</a></span></li></ul></div>

1. Load dependencies
2. Read csv files to dataframes
3. Fill missing values
4. Add date part 
5. Add extra columns (purchased on weekend, monthend, month_diff etc.
6. Aggregate by card_id
7. Aggregate by categories
8. Mark categorical columns
9. Add exta interpreted columns on aggregates
10. Load test & train csvs to dfs
11. Add date part to test & train dfs
12. Merge train & test with new & old transactions history
13. Add extra columns like age, total transactions, installments, purchase amount, first buy etc
14. Mark the outliers
15. Target encode the outliers 
16. Save to feather

### Load dependencies

In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 4
%autosave 120

Autosaving every 120 seconds

In [2]:
from fastai.io import *
from fastai.structured import *
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from pandas_summary import DataFrameSummary
from IPython.display import display
from sklearn import metrics
import feather

### Read csv files to DFs

In [3]:
PATH = '../data/elo/'

In [4]:
files = ['historical_transactions', 'new_merchant_transactions']

In [5]:
hist_trans, new_hist_trans = [pd.read_csv(f'{PATH}{c}.csv') for c in files]

### Add date part

In [6]:
add_datepart(hist_trans, 'purchase_date', drop=False)
add_datepart(new_hist_trans, 'purchase_date', drop=False)

### Train cats for the DFs

In [7]:
train_cats(hist_trans)
train_cats(new_hist_trans)

### Add extra columns (purchased on weekend, monthend, month_diff etc.

In [8]:
dfs = [hist_trans, new_hist_trans]

In [9]:
def add_extra_cols(df):
    df['purchased_on_weekend'] = (df.purchase_Dayofweek >=5).astype(int)
    df['month_diff'] = ((datetime.datetime.today() - df['purchase_date']).dt.days)//30
    df['month_diff'] += df['month_lag']
    return df

In [10]:
hist_trans, new_hist_trans = [add_extra_cols(df) for df in dfs]

In [11]:
hist_trans.shape, new_hist_trans.shape

((29112361, 29), (1963031, 29))

### Fill NAs with mode

In [12]:
def fill_nas_for_transactions_df(df):
    # Fill nas for category_3 with mode
    cols = ['merchant_id', 'category_3', 'category_2']
    for col in cols:
        df[col] = df[col].fillna(df[col].mode()[0])
    return df

In [13]:
dfs = [hist_trans, new_hist_trans]

In [14]:
hist_trans, new_hist_trans = [fill_nas_for_transactions_df(df) for df in dfs]

### Separate the authorised and non-authorised transactions

In [24]:
# hist_trans.head().T

In [25]:
authorised_trans = hist_trans.loc[hist_trans['authorized_flag'] == 'Y']
non_authorised_trans = hist_trans.loc[hist_trans['authorized_flag'] == 'N']

In [26]:
hist_trans.shape

(29112361, 29)

In [27]:
authorised_trans.shape, non_authorised_trans.shape, new_hist_trans.shape

((26595452, 29), (2516909, 29), (1963031, 29))

In [28]:
dfs = [authorised_trans, non_authorised_trans, new_hist_trans]

In [29]:
# DataFrameSummary(new_hist_trans).summary().T

In [30]:
# DataFrameSummary(authorised_trans).summary().T

In [31]:
# DataFrameSummary(non_authorised_trans).summary().T

In [32]:
# new_hist_trans.head().T

In [33]:
# authorised_trans.head().T

In [34]:
# non_authorised_trans.head().T

In [35]:
dfs = [authorised_trans, non_authorised_trans, new_hist_trans]

### proc_df to fill nas, one hot encode cats

In [36]:
%time authorised_trans_proc, y_authorised_trans, nas_authorised_trans = proc_df(authorised_trans, max_n_cat=7,ignore_flds=['purchase_date','card_id', 'merchant_id'])

CPU times: user 43.2 s, sys: 7.81 s, total: 51 s
Wall time: 10.8 s

In [37]:
%time non_authorised_trans_proc, y_non_authorised_trans, nas_non_authorised_trans = proc_df(non_authorised_trans, max_n_cat=7,ignore_flds=['purchase_date','card_id', 'merchant_id'])

CPU times: user 5.29 s, sys: 619 ms, total: 5.91 s
Wall time: 984 ms

In [38]:
%time new_trans_proc, y_new, nas_new = proc_df(new_hist_trans, max_n_cat=7,ignore_flds=['purchase_date','card_id', 'merchant_id'])

CPU times: user 2.84 s, sys: 556 ms, total: 3.4 s
Wall time: 772 ms

In [39]:
authorised_trans_proc.shape, non_authorised_trans_proc.shape, new_trans_proc.shape

((26595452, 36), (2516909, 36), (1963031, 35))

In [40]:
authorised_trans_proc.columns.values,non_authorised_trans_proc.columns.values, new_trans_proc.columns.values

(array(['purchase_date', 'card_id', 'merchant_id', 'city_id', 'installments', 'merchant_category_id',
        'month_lag', 'purchase_amount', 'category_2', 'state_id', 'subsector_id', 'purchase_Year',
        'purchase_Month', 'purchase_Week', 'purchase_Day', 'purchase_Dayofweek', 'purchase_Dayofyear',
        'purchase_Is_month_end', 'purchase_Is_month_start', 'purchase_Is_quarter_end',
        'purchase_Is_quarter_start', 'purchase_Is_year_end', 'purchase_Is_year_start', 'purchase_Elapsed',
        'purchased_on_weekend', 'month_diff', 'authorized_flag_N', 'authorized_flag_Y', 'authorized_flag_nan',
        'category_1_N', 'category_1_Y', 'category_1_nan', 'category_3_A', 'category_3_B', 'category_3_C',
        'category_3_nan'], dtype=object),
 array(['purchase_date', 'card_id', 'merchant_id', 'city_id', 'installments', 'merchant_category_id',
        'month_lag', 'purchase_amount', 'category_2', 'state_id', 'subsector_id', 'purchase_Year',
        'purchase_Month', 'purchase_Week', 'purchase_Day', 'purchase_Dayofweek', 'purchase_Dayofyear',
        'purchase_Is_month_end', 'purchase_Is_month_start', 'purchase_Is_quarter_end',
        'purchase_Is_quarter_start', 'purchase_Is_year_end', 'purchase_Is_year_start', 'purchase_Elapsed',
        'purchased_on_weekend', 'month_diff', 'authorized_flag_N', 'authorized_flag_Y', 'authorized_flag_nan',
        'category_1_N', 'category_1_Y', 'category_1_nan', 'category_3_A', 'category_3_B', 'category_3_C',
        'category_3_nan'], dtype=object),
 array(['purchase_date', 'card_id', 'merchant_id', 'city_id', 'installments', 'merchant_category_id',
        'month_lag', 'purchase_amount', 'category_2', 'state_id', 'subsector_id', 'purchase_Year',
        'purchase_Month', 'purchase_Week', 'purchase_Day', 'purchase_Dayofweek', 'purchase_Dayofyear',
        'purchase_Is_month_end', 'purchase_Is_month_start', 'purchase_Is_quarter_end',
        'purchase_Is_quarter_start', 'purchase_Is_year_end', 'purchase_Is_year_start', 'purchase_Elapsed',
        'purchased_on_weekend', 'month_diff', 'authorized_flag_Y', 'authorized_flag_nan', 'category_1_N',
        'category_1_Y', 'category_1_nan', 'category_3_A', 'category_3_B', 'category_3_C', 'category_3_nan'],
       dtype=object))

In [41]:
import gc

In [42]:
gc.collect()

109

In [43]:
# DataFrameSummary(authorised_trans_proc).summary().T

In [44]:
# DataFrameSummary(non_authorised_trans_proc).summary().T

In [45]:
# DataFrameSummary(new_trans_proc).summary().T

### Drop unnecessary columns

In [46]:
dfs = [authorised_trans_proc, non_authorised_trans_proc, new_trans_proc]

In [47]:
cols_to_drop = ['authorized_flag_Y', 'authorized_flag_nan', 'category_1_nan', 'category_3_nan']

In [48]:
authorised_trans_proc.drop(cols_to_drop, axis=1, inplace=True)

In [49]:
non_authorised_trans_proc.drop(cols_to_drop, axis=1, inplace=True)

In [50]:
new_trans_proc.drop(cols_to_drop, axis=1, inplace=True)

In [51]:
non_authorised_trans_proc.drop('authorized_flag_N', axis=1, inplace=True)

In [52]:
authorised_trans_proc.drop('authorized_flag_N', axis=1, inplace=True)

### Aggregate by card_id

In [53]:
authorised_trans_proc.columns.values

array(['purchase_date', 'card_id', 'merchant_id', 'city_id', 'installments', 'merchant_category_id',
       'month_lag', 'purchase_amount', 'category_2', 'state_id', 'subsector_id', 'purchase_Year',
       'purchase_Month', 'purchase_Week', 'purchase_Day', 'purchase_Dayofweek', 'purchase_Dayofyear',
       'purchase_Is_month_end', 'purchase_Is_month_start', 'purchase_Is_quarter_end',
       'purchase_Is_quarter_start', 'purchase_Is_year_end', 'purchase_Is_year_start', 'purchase_Elapsed',
       'purchased_on_weekend', 'month_diff', 'category_1_N', 'category_1_Y', 'category_3_A', 'category_3_B',
       'category_3_C'], dtype=object)

In [54]:
authorised_trans_proc.shape,non_authorised_trans_proc.shape, new_trans_proc.shape

((26595452, 31), (2516909, 31), (1963031, 31))

In [55]:
authorised_trans_proc.shape,non_authorised_trans_proc.shape, new_trans_proc.shape

((26595452, 31), (2516909, 31), (1963031, 31))

In [56]:
# new_trans_proc.head().T

In [57]:
def aggregate_by_card_id(df):
    unique_cols = ['city_id', 'merchant_category_id', 'merchant_id', 'state_id', 'purchase_Year',
                   'subsector_id']
    aggs = {}
    for c in unique_cols:
        aggs[c] = ['nunique'] 
    aggs['purchase_amount'] = ['sum', 'max', 'min', 'mean', 'var', 'median']
    aggs['installments'] = ['sum', 'max', 'mean', 'var', 'median']
    aggs['month_lag'] = ['sum', 'max', 'min', 'mean', 'var', 'median']
    aggs['purchase_date'] = [np.min, np.max, np.ptp]
    aggs['card_id'] = ['size']
    aggs['purchased_on_weekend'] = ['sum', 'mean']
    aggs['month_diff'] = ['sum', 'max', 'min', 'mean', 'var', 'median']
    aggs['category_1_N'] = ['sum', 'mean']
    aggs['category_1_Y'] = ['sum', 'mean']
    aggs['category_2'] = ['mean', 'sum', 'size']
    aggs['category_3_A'] = ['mean', 'sum' ,'size']
    aggs['category_3_B' ] = ['mean', 'sum', 'size']
    aggs['category_3_C' ] = ['mean', 'sum', 'size']
    
    for col in ['category_2', 'category_3_A', 'category_3_B', 'category_3_C']:
        df[col+'_mean2'] = df.groupby([col])['purchase_amount'].transform('mean')
        aggs[col+'_mean2'] = ['mean']    

    new_df = df.groupby(['card_id']).agg(aggs)
    new_df.columns = ['_'.join(col).strip() for col in new_df.columns.values]
    new_df.reset_index(inplace=True)
    other_df = (df.groupby('card_id')
          .size()
          .reset_index(name='transactions_count'))
    
    new_df = pd.merge(other_df, new_df, on='card_id', how='left')
    new_df["purchase_date_ptp"] = new_df["purchase_date_ptp"].dt.days    
    return new_df

In [58]:
dfs_e = [authorised_trans_proc, non_authorised_trans_proc, new_trans_proc]

In [59]:
%time authorised_trans_proc_agg, non_authorised_trans_proc_agg, new_trans_proc_agg = [aggregate_by_card_id(df) for df in dfs_e]

CPU times: user 4min 6s, sys: 10.2 s, total: 4min 16s
Wall time: 2min 46s

### Add exta interpreted columns on aggregates

In [60]:
dfs_agg = [authorised_trans_proc_agg, non_authorised_trans_proc_agg, new_trans_proc_agg]

In [61]:
authorised_trans_proc_agg.shape, non_authorised_trans_proc_agg.shape, new_trans_proc_agg.shape

((325540, 57), (325540, 57), (290001, 57))

In [62]:
# authorised_trans_proc_agg.head().T

In [63]:
def add_extra_cols_on_agg(df):
    df['inverse_avg_transactions_per_day'] = df['purchase_date_ptp']/df['card_id_size']
    df['days_since_last_transaction'] = (datetime.datetime.today() - df['purchase_date_amax']).dt.days
    df['category_3_sum_total'] = df['category_3_A_sum'] + df['category_3_B_sum'] + df['category_3_C_sum']
    df['category_3_mean_total'] = (df['category_3_A_mean'] + df['category_3_B_mean'] + df['category_3_C_mean'])/3
    return df

In [64]:
[authorised_trans_proc_agg, non_authorised_trans_proc_agg, new_trans_proc_agg] = [add_extra_cols_on_agg(df) for df in dfs_agg]

In [65]:
authorised_trans_proc_agg.to_feather('authorised_trans_proc_agg')
non_authorised_trans_proc_agg.to_feather('non_authorised_trans_proc_agg')
new_trans_proc_agg.to_feather('new_trans_proc_agg')

In [66]:
authorised_trans_proc_agg = feather.read_dataframe('authorised_trans_proc_agg')
non_authorised_trans_proc_agg = feather.read_dataframe('non_authorised_trans_proc_agg')
new_trans_proc_agg = feather.read_dataframe('new_trans_proc_agg')

In [67]:
authorised_trans_proc_agg.shape, non_authorised_trans_proc_agg.shape, new_trans_proc_agg.shape

((325540, 61), (325540, 61), (290001, 61))

### Add monthly aggregates

In [68]:
def aggregate_per_month(history):
    grouped = history.groupby(['card_id', 'month_lag'])

    agg_func = {
            'purchase_amount': ['count', 'sum', 'mean', 'min', 'max', 'std'],
            'installments': ['count', 'sum', 'mean', 'min', 'max', 'std'],
            }

    intermediate_group = grouped.agg(agg_func)
    intermediate_group.columns = ['_'.join(col).strip() for col in intermediate_group.columns.values]
    intermediate_group.reset_index(inplace=True)

    final_group = intermediate_group.groupby('card_id').agg(['mean', 'std'])
    final_group.columns = ['_'.join(col).strip() for col in final_group.columns.values]
    final_group.reset_index(inplace=True)
    
    return final_group

In [69]:
[authorised_trans_proc_m, non_authorised_trans_proc_m, new_trans_proc_m] = [aggregate_per_month(d) for d in dfs_e]

### Add successive aggregates

In [70]:
def successive_aggregates(df, field1, field2):
    t = df.groupby(['card_id', field1])[field2].mean()
    u = pd.DataFrame(t).reset_index().groupby('card_id')[field2].agg(['mean', 'min', 'max', 'std'])
    u.columns = [field1 + '_' + field2 + '_' + col for col in u.columns.values]
    u.reset_index(inplace=True)
    return u

In [71]:
# authorised_trans_proc.head().T

In [72]:
additional_fields_at = successive_aggregates(authorised_trans_proc, 'category_1_Y', 'purchase_amount')
additional_fields_at = additional_fields_at.merge(successive_aggregates(authorised_trans_proc, 'installments', 'purchase_amount'),
                                            on = 'card_id', how='left')
additional_fields_at = additional_fields_at.merge(successive_aggregates(authorised_trans_proc, 'city_id', 'purchase_amount'),
                                            on = 'card_id', how='left')
additional_fields_at = additional_fields_at.merge(successive_aggregates(authorised_trans_proc, 'category_1_Y', 'installments'),
                                            on = 'card_id', how='left')

In [73]:
# non_authorised_trans_proc.head().T

In [74]:
additional_fields_nat = successive_aggregates(non_authorised_trans_proc, 'category_1_Y', 'purchase_amount')
additional_fields_nat = additional_fields_nat.merge(successive_aggregates(non_authorised_trans_proc, 'installments', 'purchase_amount'),
                                            on = 'card_id', how='left')
additional_fields_nat = additional_fields_nat.merge(successive_aggregates(non_authorised_trans_proc, 'city_id', 'purchase_amount'),
                                            on = 'card_id', how='left')
additional_fields_nat = additional_fields_nat.merge(successive_aggregates(non_authorised_trans_proc, 'category_1_Y', 'installments'),
                                            on = 'card_id', how='left')

In [75]:
additional_fields_new = successive_aggregates(new_trans_proc, 'category_1_Y', 'purchase_amount')
additional_fields_new = additional_fields_new.merge(successive_aggregates(new_trans_proc, 'installments', 'purchase_amount'),
                                            on = 'card_id', how='left')
additional_fields_new = additional_fields_new.merge(successive_aggregates(new_trans_proc, 'city_id', 'purchase_amount'),
                                            on = 'card_id', how='left')
additional_fields_new = additional_fields_new.merge(successive_aggregates(new_trans_proc, 'category_1_Y', 'installments'),
                                            on = 'card_id', how='left')

### Merge monthly aggregates and successive aggregates dfs with other aggregate dfs

In [76]:
additional_fields_new.shape, additional_fields_nat.shape, additional_fields_at.shape

((290001, 17), (325540, 17), (325540, 17))

In [77]:
authorised_trans_proc_m.shape, non_authorised_trans_proc_m.shape, new_trans_proc_m.shape

((325540, 27), (325540, 27), (290001, 27))

In [78]:
authorised_trans_proc_agg.shape, non_authorised_trans_proc_agg.shape, new_trans_proc_agg.shape

((325540, 61), (325540, 61), (290001, 61))

In [79]:
def join_dfs(left, right, left_on, right_on=None, suffix='_old'):
    if right_on is None: right_on = left_on
    return left.merge(right, how='left', left_on=left_on, right_on=right_on, suffixes=("", suffix))

In [80]:
df_new = join_dfs(additional_fields_new, new_trans_proc_agg, left_on='card_id')

In [81]:
df_new = join_dfs(df_new, new_trans_proc_m, left_on='card_id')

In [82]:
df_auth = join_dfs(additional_fields_at, authorised_trans_proc_agg, left_on='card_id')
df_auth = join_dfs(df_auth, authorised_trans_proc_m, left_on='card_id')

In [83]:
df_non_auth = join_dfs(additional_fields_nat, non_authorised_trans_proc_agg, left_on='card_id')
df_non_auth = join_dfs(df_non_auth, non_authorised_trans_proc_m, left_on='card_id')

In [84]:
df_new.shape, df_auth.shape, df_non_auth.shape

((290001, 103), (325540, 103), (325540, 103))

In [85]:
df_new.to_feather('df_new')
df_auth.to_feather('df_auth')
df_non_auth.to_feather('df_non_auth')

In [86]:
df_new = feather.read_dataframe('df_new')
df_auth = feather.read_dataframe('df_auth')
df_non_auth= feather.read_dataframe('df_non_auth')

### Load test & train DFs

In [87]:
PATH = 'data/elo/'

In [88]:
train, test = [pd.read_csv(f'{PATH}{c}') for c in ['train.csv', 'test.csv']]

### Add date part to test & train dfs

In [89]:
add_datepart(train, 'first_active_month', drop=False)
add_datepart(test, 'first_active_month', drop=False)

### Merge train & test with new & old transactions history

In [90]:
def join_dfs(left, right, left_on, right_on=None, suffix='_old'):
    if right_on is None: right_on = left_on
    return left.merge(right, how='left', left_on=left_on, right_on=right_on, suffixes=("", suffix))

In [91]:
# authorised_trans_proc_agg.head().T

In [92]:
# non_authorised_trans_proc.head().T

In [93]:
# authorised_trans_proc_agg, non_authorised_trans_proc, new_trans_proc_agg

(                card_id  transactions_count  city_id_nunique  \
 0       C_ID_00007093c1                 114                4
 1       C_ID_0001238066                 120               18
 2       C_ID_0001506ef0                  62                3
 3       C_ID_0001793786                 189                9
 4       C_ID_000183fdda                 137                9
 5       C_ID_00024e244b                  53                3
 6       C_ID_0002709b5a                  67                4
 7       C_ID_00027503e2                  24                2
 8       C_ID_000298032a                  28                5
 9       C_ID_0002ba3c2e                  55                3
 10      C_ID_0002c7c2c1                  58                3
 11      C_ID_00032df08f                 125                5
 12      C_ID_0003754056                  35                3
 13      C_ID_000377f6a0                  22                2
 14      C_ID_0003be3c83                 146                6
 15      C_ID_0003f41435                 257               12
 16      C_ID_00042d509c                  18                4
 17      C_ID_0004587331                  12                1
 18      C_ID_0004725b87                  71                2
 19      C_ID_0004888ddd                  36                2
 20      C_ID_0004b68c49                   5                2
 21      C_ID_0004c2a5ab                  70                5
 22      C_ID_00057b99fe                  33                5
 23      C_ID_000599daf9                  33                3
 24      C_ID_0005b2f279                  16                4
 25      C_ID_0005b5804f                   8                2
 26      C_ID_0005f16cc8                 136                8
 27      C_ID_0006152db8                  76                5
 28      C_ID_000616f4a8                  36                8
 29      C_ID_000664aa02                  35                4
 ...                 ...                 ...              ...
 325510  C_ID_fffb79fb56                  21                1
 325511  C_ID_fffb9ea3f6                  42                2
 325512  C_ID_fffba72dc5                  72                5
 325513  C_ID_fffbdf036b                  78                2
 325514  C_ID_fffbee5c24                  20                2
 325515  C_ID_fffc96bf24                 201                3
 325516  C_ID_fffcb74f49                  96                7
 325517  C_ID_fffcf66e12                  33                3
 325518  C_ID_fffd070e0e                  36                5
 325519  C_ID_fffd1207a8                 766                7
 325520  C_ID_fffd24dcf3                  13                2
 325521  C_ID_fffd337484                  31                6
 325522  C_ID_fffd345048                  58                6
 325523  C_ID_fffd351e7f                 210               42
 325524  C_ID_fffd93c8bf                 127                6
 325525  C_ID_fffd943b91                  49                4
 325526  C_ID_fffdad8aa0                 118                8
 325527  C_ID_fffde15ab6                  72                7
 325528  C_ID_fffdf34798                  57                1
 325529  C_ID_fffe29a04a                  84                8
 325530  C_ID_fffe78b232                 343               26
 325531  C_ID_fffe866457                  55                4
 325532  C_ID_fffea6de74                 395                8
 325533  C_ID_fffeced303                 166                4
 325534  C_ID_fffeed3a89                 165               15
 325535  C_ID_ffff1d9928                   9                2
 325536  C_ID_ffff579d3a                  99                7
 325537  C_ID_ffff756266                  14                2
 325538  C_ID_ffff828181                 166               11
 325539  C_ID_fffffd5772                  75                4

         merchant_category_id_nunique  merchant_id_nunique  state_id_nunique  \
 0                                 18                   28                 3
 1                                 29                   65                 6
 2                                 19                   28                 2
 3                                 45                  114                 4
 4                                 34                   71                 7
 5                                 10                   18                 2
 6                                 17                   32                 4
 7                                  6                   11                 2
 8                                 12                   20                 2
 9                                 21                   32                 2
 10                                25                   38                 1
 11                                40                   58                 3
 12                                12                   14                 2
 13                                12                   14                 2
 14                                33                   67                 2
 15                                33                  111                 7
 16                                 9                   10                 3
 17                                 5                    8                 1
 18                                18                   31                 2
 19                                12                   19                 2
 20                                 5                    5                 2
 21                                22                   40                 3
 22                                12                   25                 1
 23                                18                   22                 2
 24                                 6                    7                 3
 25                                 5                    5                 2
 26                                32                   65                 8
 27                                19                   26                 3
 28                                18                   29                 4
 29                                15                   25                 1
 ...                              ...                  ...               ...
 325510                             4                    7                 1
 325511                            13                   17                 1
 325512                            18                   30                 1
 325513                            12                   31                 1
 325514                            11                   16                 1
 325515                            44                   77                 3
 325516                            16                   34                 2
 325517                             9                   11                 2
 325518                            15                   23                 1
 325519                            39                  125                 3
 325520                             9                   11                 2
 325521                            18                   20                 4
 325522                            18                   29                 3
 325523                            24                  135                14
 325524                            28                   56                 4
 325525                            15                   22                 2
 325526                            29                   52                 1
 325527                            17                   32                 3
 325528                             9                   18                 1
 325529                            28                   52                 2
 325530                            25                  143                 4
 325531                            13                   26                 2
 325532                            51                  148                 5
 325533                            21                   32                 3
 325534                            42                  115                 9
 325535                             4                    7                 2
 325536                            27                   61                 2
 325537                            10                   10                 2
 325538                            42                   85                 7
 325539                            14                   19                 3

         purchase_Year_nunique  subsector_id_nunique  purchase_amount_sum  \
 0                           2                    13           -62.443076
 1                           2                    17           -70.657273
 2                           2                    12           -31.696098
 3                           1                    22           -24.960674
 4                           2                    20           -67.896557
 5                           2                     8           -33.246142
 6                           2                    12           -43.940841
 7                           2                     6           -17.774786
 8                           2                    10           -14.756500
 9                           1                    15           -35.058310
 10                          2                    11           -38.129924
 11                          1                    16           -47.693608
 12                          1                     8           -24.200483
 13                          2                     9           -13.029909
 14                          2                    20           -93.405609
 15                          2                    18          -183.623508
 16                          1                     8           -11.649093
 17                          2                     5            -8.570341
 18                          2                    10           -44.262258
 19                          2                     9           -25.343655
 20                          1                     5            -2.522185
 21                          2                    13           -44.206390
 22                          2                     9           -23.851567
 23                          2                    12           -19.236490
 24                          1                     5           -10.090693
 25                          2                     4            -5.430055
 26                          2                    18           -82.918967
 27                          2                    11           -54.030603
 28                          2                    13           -20.894034
 29                          2                     9           -22.401839
 ...                       ...                   ...                  ...
 325510                      1                     4            -8.558260
 325511                      2                     9           -29.152695
 325512                      2                    13           -33.545741
 325513                      1                    10           -55.166938
 325514                      1                     7            -7.319850
 325515                      2                    22          -118.633289
 325516                      2                    10           -58.879974
 325517                      2                     7           -22.670063
 325518                      2                     9           -22.654766
 325519                      2                    19          -534.895299
 325520                      2                     8            10.669785
 325521                      1                    13            -1.272685
 325522                      2                    12           -32.851321
 325523                      2                    13          -114.223879
 325524                      2                    17           -75.175445
 325525                      2                    12           -33.866347
 325526                      2                    15           -81.411958
 325527                      2                    13           -48.764246
 325528                      2                     8           -37.961011
 325529                      2                    16           -53.045600
 325530                      2                    12          -224.697517
 325531                      2                     7           -31.634248
 325532                      2                    24          -233.201711
 325533                      2                     8          -114.100091
 325534                      2                    20           -89.904642
 325535                      2                     4            -5.537901
 325536                      2                    15           -69.678732
 325537                      1                     7            -6.745010
 325538                      2                    23          -104.608520
 325539                      2                    10           -51.409273

         purchase_amount_max          ...            category_3_C_sum  \
 0                  1.206539          ...                        18.0
 1                  0.768095          ...                        32.0
 2                  1.493545          ...                         0.0
 3                  4.554145          ...                         0.0
 4                  2.764788          ...                        33.0
 5                  2.258395          ...                         0.0
 6                 -0.336684          ...                        12.0
 7                 -0.734135          ...                         0.0
 8                  2.577843          ...                         0.0
 9                 -0.097011          ...                         0.0
 10                -0.296112          ...                         0.0
 11                 2.679137          ...                        14.0
 12                -0.482501          ...                         0.0
 13                -0.281086          ...                         0.0
 14                 1.134802          ...                        25.0
 15                -0.489894          ...                         0.0
 16                 0.135885          ...                         2.0
 17                -0.624742          ...                         0.0
 18                -0.145847          ...                        20.0
 19                -0.626696          ...                         0.0
 20                 0.277735          ...                         1.0
 21                -0.296112          ...                        23.0
 22                -0.566590          ...                         0.0
 23                -0.145847          ...                         0.0
 24                -0.466213          ...                         0.0
 25                -0.604156          ...                         0.0
 26                 0.267547          ...                         0.0
 27                -0.644728          ...                         0.0
 28                 0.223805          ...                         5.0
 29                 0.034471          ...                         0.0
 ...                     ...          ...                         ...
 325510            -0.075974          ...                         1.0
 325511            -0.491427          ...                         0.0
 325512             1.631023          ...                         0.0
 325513            -0.583720          ...                         0.0
 325514             1.083321          ...                        11.0
 325515             1.666019          ...                        12.0
 325516             0.024298          ...                         0.0
 325517            -0.560714          ...                         0.0
 325518            -0.296112          ...                         0.0
 325519             1.054771          ...                         0.0
 325520             5.248670          ...                        11.0
 325521             1.657334          ...                        20.0
 325522             2.181098          ...                         0.0
 325523             1.639182          ...                         0.0
 325524             0.528843          ...                         0.0
 325525            -0.386332          ...                         5.0
 325526            -0.371245          ...                         0.0
 325527             0.440187          ...                         3.0
 325528             2.859455          ...                         0.0
 325529             0.410134          ...                         0.0
 325530             0.626666          ...                         3.0
 325531             0.016214          ...                         4.0
 325532             3.761046          ...                        23.0
 325533            -0.145847          ...                         8.0
 325534             3.758641          ...                        16.0
 325535             0.004418          ...                         1.0
 325536            -0.491457          ...                         0.0
 325537             0.229740          ...                         5.0
 325538             0.109528          ...                        19.0
 325539            -0.311139          ...                         4.0

         category_3_C_size  category_2_mean2_mean  category_3_A_mean2_mean  \
 0                     114              -0.576449                -0.534588
 1                     120              -0.591905                -0.537080
 2                      62              -0.572625                -0.634275
 3                     189              -0.587557                -0.634275
 4                     137              -0.573808                -0.537499
 5                      53              -0.573128                -0.634275
 6                      67              -0.584185                -0.536076
 7                      24              -0.573681                -0.634275
 8                      28              -0.592634                -0.634275
 9                      55              -0.582362                -0.634275
 10                     58              -0.592634                -0.634275
 11                    125              -0.592469                -0.534588
 12                     35              -0.592634                -0.634275
 13                     22              -0.574777                -0.634275
 14                    146              -0.592634                -0.535271
 15                    257              -0.592436                -0.634275
 16                     18              -0.584593                -0.540126
 17                     12              -0.571958                -0.634275
 18                     71              -0.592634                -0.534588
 19                     36              -0.572532                -0.634275
 20                      5              -0.592634                -0.534588
 21                     70              -0.592565                -0.536012
 22                     33              -0.592634                -0.634275
 23                     33              -0.573211                -0.634275
 24                     16              -0.592331                -0.534588
 25                      8              -0.574542                -0.634275
 26                    136              -0.574766                -0.634275
 27                     76              -0.591853                -0.634275
 28                     36              -0.591689                -0.534588
 29                     35              -0.592634                -0.634275
 ...                   ...                    ...                      ...

In [94]:
train_df = join_dfs(train, df_new, left_on='card_id')

In [95]:
train_df = join_dfs(train_df, df_auth, left_on='card_id', suffix='_auth')

In [96]:
# train_df = join_dfs(train_df, df_non_auth, left_on='card_id', suffix='_n_auth')

In [97]:
test_df = join_dfs(test, df_new, left_on='card_id')
test_df = join_dfs(test_df, df_auth, left_on='card_id', suffix='_auth')
# test_df = join_dfs(test_df, df_non_auth, left_on='card_id', suffix='_n_auth')

In [98]:
test_df.shape, train_df.shape

((123623, 324), (201917, 325))

### Add extra columns like age, total transactions, installments, purchase amount, first buy etc

In [99]:
# display(train_df.columns.values)

In [100]:
for df in [train_df, test_df]:
    df['elapsed_time'] = (datetime.datetime.today() - df['first_active_month']).dt.days
    df['card_id_total'] = df['card_id_size']+df['card_id_size_auth']+df['card_id_size_n_auth']
    df["month_lag_sum_total"]= df["month_lag_sum_auth"]+ df["month_lag_sum"]
    df['purchase_amount_total'] = df['purchase_amount_sum']+df['purchase_amount_sum_auth'] + df['purchase_amount_sum_n_auth']
    df['installments_total'] = df['installments_sum'] + df['installments_sum_auth'] + df['installments_sum_n_auth']
    df["category_1_Y_sum_total"] = df["category_1_Y_sum_auth"]+ df["category_1_Y_sum"] + df["category_1_Y_sum_n_auth"]
    df["category_2_sum_total"]= df["category_2_sum_auth"]+ df["category_2_sum"] + df["category_2_sum_n_auth"]
    df["category_3_A_total"]= df["category_3_A_sum"]+ df["category_3_A_sum_auth"] + df["category_3_A_sum_n_auth"]
    df["category_3_B_total"]= df["category_3_B_sum"]+ df["category_3_B_sum_auth"] + df["category_3_B_sum_n_auth"]
    df["category_3_C_total"]= df["category_3_C_sum"]+ df["category_3_C_sum_auth"] + df["category_3_C_sum_n_auth"]
    df["category_3_sum_total_all"]= df["category_3_sum_total"]+ df["category_3_sum_total_auth"] + df["category_3_sum_total_n_auth"]
    df['hist_first_buy'] = (df[['purchase_date_amin_auth', 'purchase_date_amin_n_auth']].min(axis=1) - df['first_active_month']).dt.days
    df['new_first_buy'] = (df['purchase_date_amin'] - df['first_active_month']).dt.days

In [8]:
train_df[['merchant_id_nunique', 'merchant_id_nunique_auth', 'merchant_id_nunique_n_auth']].head()

   merchant_id_nunique  merchant_id_nunique_auth  merchant_id_nunique_n_auth
0                 23.0                        93                          13
1                  6.0                       141                           9
2                  1.0                        13                           1
3                  7.0                        50                           0
4                 36.0                        65                           2

In [101]:
train_df.shape, test_df.shape

((201917, 338), (123623, 337))

In [102]:
# train_df.head().T

### Mark the outliers

In [4]:
# train_df.to_feather('train_df_proc_new_m')
# test_df.to_feather('test_df_proc_new_m')
train_df = feather.read_dataframe('train_df_proc_new_m')
test_df = feather.read_dataframe('test_df_proc_new_m')

In [5]:
train_df.head().T

,0,1,2,3,4
first_active_month,2017-06-01 00:00:00,2017-01-01 00:00:00,2016-08-01 00:00:00,2017-09-01 00:00:00,2017-11-01 00:00:00
card_id,C_ID_92a2005557,C_ID_3d0044924f,C_ID_d639edf6cd,C_ID_186d6a6901,C_ID_cdbd2c0db2
feature_1,0.0131446,0.0107116,0.0106099,0.0107116,0.00805849
feature_2,0.00875212,0.0113848,0.00875212,0.0141664,0.0141664
feature_3,0.0114275,0.0102828,0.0102828,0.0102828,0.0102828
target,-0.820283,0.392913,0.688056,0.142495,-0.159749
first_active_monthYear,2017,2017,2016,2017,2017
first_active_monthMonth,6,1,8,9,11
first_active_monthWeek,22,52,31,35,44
first_active_monthDay,1,1,1,1,1
first_active_monthDayofweek,3,6,0,4,2
first_active_monthDayofyear,152,1,214,244,305
first_active_monthIs_month_end,False,False,False,False,False
first_active_monthIs_month_start,True,True,True,True,True
first_active_monthIs_quarter_end,False,False,False,False,False
first_active_monthIs_quarter_start,False,True,False,False,False
first_active_monthIs_year_end,False,False,False,False,False
first_active_monthIs_year_start,False,True,False,False,False
first_active_monthElapsed,1496275200,1483228800,1470009600,1504224000,1509494400
category_1_Y_purchase_amount_mean,-0.575835,-0.725956,-0.700326,-0.664077,-0.492765
category_1_Y_purchase_amount_min,-0.575835,-0.725956,-0.700326,-0.665244,-0.561099
category_1_Y_purchase_amount_max,-0.575835,-0.725956,-0.700326,-0.66291,-0.424431
category_1_Y_purchase_amount_std,NaN,NaN,NaN,0.00165047,0.0966388
installments_purchase_amount_mean,-0.575835,-0.725956,-0.700326,-0.624006,-0.358858
installments_purchase_amount_min,-0.575835,-0.725956,-0.700326,-0.681272,-0.571202
installments_purchase_amount_max,-0.575835,-0.725956,-0.700326,-0.56674,-0.175915
installments_purchase_amount_std,NaN,NaN,NaN,0.0809864,0.199277
city_id_purchase_amount_mean,-0.458993,-0.725956,-0.700326,-0.664077,-0.53472
city_id_purchase_amount_min,-0.606593,-0.725956,-0.700326,-0.665244,-0.671174
city_id_purchase_amount_max,-0.296112,-0.725956,-0.700326,-0.66291,-0.326762
...,...,...,...,...,...
purchase_amount_max_mean_n_auth,-0.608962,0.15432,-0.669484,NaN,3.34005
purchase_amount_max_std_n_auth,0.127612,0.970537,0.0452109,NaN,5.44895
purchase_amount_std_mean_n_auth,0.0510777,0.535838,NaN,NaN,0.0578573
purchase_amount_std_std_n_auth,0.0502026,0.75779,NaN,NaN,0.0818226
installments_count_mean_n_auth,2.16667,1.83333,1,NaN,2.5
installments_count_std_n_auth,1.16905,1.60208,0,NaN,0.707107
installments_sum_mean_n_auth,0.666667,7,0,NaN,19
installments_sum_std_n_auth,0.816497,7.64199,0,NaN,24.0416
installments_mean_mean_n_auth,0.319444,4.03333,0,NaN,6.5
installments_mean_std_n_auth,0.423007,3.52231,0,NaN,7.77817
installments_min_mean_n_auth,0.166667,3.5,0,NaN,6.5
installments_min_std_n_auth,0.408248,3.72827,0,NaN,7.77817
installments_max_mean_n_auth,0.5,5,0,NaN,6.5
installments_max_std_n_auth,0.547723,4.28952,0,NaN,7.77817
installments_std_mean_n_auth,0.269338,1.78185,NaN,NaN,0
installments_std_std_n_auth,0.312603,2.51992,NaN,NaN,0
elapsed_time,594,745,898,502,441
card_id_total,283,356,44,84,169
month_lag_sum_total,-925,-1703,-346,-206,-113
purchase_amount_total,-179.213,-214.362,-29.8677,-54.1457,-68.6139
installments_total,4,549,0,89,217
category_1_Y_sum_total,0,31,0,13,17
category_2_sum_total,295,356,204,261,583
category_3_A_total,279,2,44,3,1
category_3_B_total,4,282,0,74,160
category_3_C_total,0,72,0,7,8
category_3_sum_total_all,283,356,44,84,169
hist_first_buy,26,5,163,25,11
new_first_buy,277,396,635,187,121
outliers,0,0,0,0,0

In [104]:
train_df['outliers'] = 0
train_df.loc[train_df['target'] < -30, 'outliers'] = 1
train_df['outliers'].value_counts()

0    199710
1      2207
Name: outliers, dtype: int64

### Target encode the outliers - no improvements

In [6]:
for f in ['feature_1','feature_2','feature_3']:
    order_label = train_df.groupby([f])['outliers'].mean()
    train_df[f] = train_df[f].map(order_label)
    test_df[f] = test_df[f].map(order_label)

In [7]:
train_df.to_feather('train_df_proc_new_m')
test_df.to_feather('test_df_proc_new_m')